# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06wallet\"!\n\x0e\x42\x61lanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"e\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x05\"P\n\x15WalletMutationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"\xa8\x01\n\x16WalletMutationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x06 \x01(\t\x12\x12\n\nentry_type\x18\x07 \x01(\t\x12\x0e\n\x06\x61mount\x18\x08 \x01(\x05\x32\xbe\x02\n\rWalletService\x12=\n\nGetBalance\x12\x16.wallet.BalanceRequest\x1a\x17.wallet.BalanceResponse\x12M\n\x0c\x44\x65\x62itCredits\x12\x1d.wallet.WalletMutationRequest\x1a\x1e.wallet.WalletMutationResponse\x12N\n\rRefundCredits\x12\x1d.wallet.WalletMutationRequest\x1a\x1e.wallet.WalletMutationResponse\x12O\n\x0e\x46orfeitCredits\x12\x1d.wallet.WalletMutationRequest\x1a\x1e.wallet.WalletMutationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BALANCEREQUEST']._serialized_start=24
  _globals['_BALANCEREQUEST']._serialized_end=57
  _globals['_BALANCERESPONSE']._serialized_start=59
  _globals['_BALANCERESPONSE']._serialized_end=160
  _globals['_WALLETMUTATIONREQUEST']._serialized_start=162
  _globals['_WALLETMUTATIONREQUEST']._serialized_end=242
  _globals['_WALLETMUTATIONRESPONSE']._serialized_start=245
  _globals['_WALLETMUTATIONRESPONSE']._serialized_end=413
  _globals['_WALLETSERVICE']._serialized_start=416
  _globals['_WALLETSERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
