# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.services import wallet_pb2 as wallet__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/wallet.WalletService/GetBalance',
                request_serializer=wallet__pb2.BalanceRequest.SerializeToString,
                response_deserializer=wallet__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.DebitCredits = channel.unary_unary(
                '/wallet.WalletService/DebitCredits',
                request_serializer=wallet__pb2.WalletMutationRequest.SerializeToString,
                response_deserializer=wallet__pb2.WalletMutationResponse.FromString,
                _registered_method=True)
        self.RefundCredits = channel.unary_unary(
                '/wallet.WalletService/RefundCredits',
                request_serializer=wallet__pb2.WalletMutationRequest.SerializeToString,
                response_deserializer=wallet__pb2.WalletMutationResponse.FromString,
                _registered_method=True)
        self.ForfeitCredits = channel.unary_unary(
                '/wallet.WalletService/ForfeitCredits',
                request_serializer=wallet__pb2.WalletMutationRequest.SerializeToString,
                response_deserializer=wallet__pb2.WalletMutationResponse.FromString,
                _registered_method=True)


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DebitCredits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundCredits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForfeitCredits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=wallet__pb2.BalanceRequest.FromString,
                    response_serializer=wallet__pb2.BalanceResponse.SerializeToString,
            ),
            'DebitCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.DebitCredits,
                    request_deserializer=wallet__pb2.WalletMutationRequest.FromString,
                    response_serializer=wallet__pb2.WalletMutationResponse.SerializeToString,
            ),
            'RefundCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundCredits,
                    request_deserializer=wallet__pb2.WalletMutationRequest.FromString,
                    response_serializer=wallet__pb2.WalletMutationResponse.SerializeToString,
            ),
            'ForfeitCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.ForfeitCredits,
                    request_deserializer=wallet__pb2.WalletMutationRequest.FromString,
                    response_serializer=wallet__pb2.WalletMutationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.WalletService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetBalance',
            wallet__pb2.BalanceRequest.SerializeToString,
            wallet__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DebitCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/DebitCredits',
            wallet__pb2.WalletMutationRequest.SerializeToString,
            wallet__pb2.WalletMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/RefundCredits',
            wallet__pb2.WalletMutationRequest.SerializeToString,
            wallet__pb2.WalletMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForfeitCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/ForfeitCredits',
            wallet__pb2.WalletMutationRequest.SerializeToString,
            wallet__pb2.WalletMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
